name: Run tests

on:
  push:
    branches: ['main']
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-22.04', 'ubuntu-24.04']
        ruby-version: ['3.3', '3.4']

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Build Gem
        run: bundle exec rake compile

      - name: Run tests
        run: bundle exec rake test
