name: Run tests

on:
  push:
    branches: ['main']
  pull_request:

env:
  CARGO_TERM_COLOR: always
  RB_SYS_CARGO_PROFILE: dev

jobs:
  test:
    strategy:
      matrix:
        os: ['ubuntu-20.04', 'ubuntu-22.04', 'ubuntu-24.04']
        ruby-version: ['3.3', '3.4']
        pf2_variant: ['pf2', 'pf2c']

    runs-on: ${{ matrix.os }}

    env:
      PF2_PF2C: ${{ matrix.pf2_variant == 'pf2c' && '1' || '0' }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Build Gem
        run: bundle exec rake compile

      - name: Run tests (Ruby)
        run: bundle exec rake test

      - name: Run tests (Rust)
        run: cargo test --verbose
